---
title: "Visualizing outage data"
date: "today"
---

```{r setup, include=FALSE}
library(targets)
library(tidytable)
library(forcats)
library(ggplot2)
library(ggtext)
library(ggrepel)
library(scales)

theme_set(theme_minimal(base_size = 18) +
            theme(panel.grid = element_blank(),
                  plot.background = element_rect(fill = "#fcfcfc",
                                                 color = "#fcfcfc")))

tar_load(matches("sai[df]i"), store = "../_targets")

median_tag <- "<span style = 'color:#530003;'><strong>US median*</strong></span>"
median_red <- "#530003"
base_red <- "#FF4647"
```

## SAIDI

For each state, total duration of annual interruptions in hours. Source for US average is this EIA [article](https://www.eia.gov/todayinenergy/detail.php?id=54639), including major events

```{r state_saidi}
state_saidi %>% 
  bind_rows(
    data.frame(
      state = median_tag,
      # Technically, they say "just over seven hours"
      # so I added 5%
      saidi = 7*1.05
    )
  ) %>% 
  mutate(
    state = fct_reorder(state, saidi)
  ) %>% 
  ggplot(aes(x = saidi,
             y = state)) +
  geom_col(aes(fill = state == median_tag)) +
  scale_fill_manual(values = c(base_red,
                               median_red)) +
  labs(caption = "*including major events") +
  guides(fill = "none") +
  theme(panel.grid.major.x = element_line("grey90"),
        axis.text.y = element_markdown(),
        axis.title = element_blank())
```

then, for each county within those states

```{r county_saidi, fig.height=6}
county_saidi %>% 
  mutate(
    state = fct_reorder(state, saidi)
  ) %>% 
  ggplot(aes(x = saidi,
             y = state)) +
  geom_violin(draw_quantiles = c(0.05, 0.5, 0.95),
              fill = base_red) +
  geom_vline(xintercept = 7*1.05,
             color = median_red,
             linewidth = rel(1.1)) +
  scale_x_sqrt(breaks = c(0,10,100,200,300)) +
  labs(title = paste("States' county SAIDIs compared to the", median_tag), 
       caption = "*including major events") +
  guides(fill = "none") +
  theme(panel.grid.major.x = element_line("grey90"),
        axis.title = element_blank(),
        title = element_markdown(size = rel(0.8)))
```

## SAIFI

First, state-level results

```{r state_saifi}
state_saifi %>% 
  bind_rows(
    data.frame(
      state = median_tag,
      # I am "transcribing" this value from the chart the EIA provides
      saifi = 1.4
    )
  ) %>% 
  mutate(
    state = fct_reorder(state, saifi)
  ) %>% 
  ggplot(aes(x = saifi,
             y = state)) +
  geom_col(aes(fill = state == median_tag)) +
  scale_fill_manual(values = c(base_red,
                               median_red)) +
  labs(caption = "*including major events") +
  guides(fill = "none") +
  theme(panel.grid.major.x = element_line("grey90"),
        axis.text.y = element_markdown(),
        axis.title = element_blank())
```

then, for each county within those states

```{r county_saifi, fig.height=6}
county_saifi %>% 
  mutate(
    state = fct_reorder(state, saifi)
  ) %>% 
  ggplot(aes(x = saifi,
             y = state)) +
  geom_violin(draw_quantiles = c(0.05, 0.5, 0.95),
              fill = base_red) +
  geom_vline(xintercept = 1.4,
             color = median_red,
             linewidth = rel(1.1)) +
  scale_x_sqrt(breaks = c(0,1,10,20,30,40)) +
  labs(title = paste("States' county SAIFIs compared to the", median_tag),
       caption = "*including major events") +
  guides(fill = "none") +
  theme(panel.grid.major.x = element_line("grey90"),
        axis.title = element_blank(),
        title = element_markdown(size = rel(0.8)))
```

## Scatterplot!

```{r scatter, fig.asp=1/2}
inner_join(
  state_saidi,
  state_saifi,
  by = "state"
) %>% 
  bind_rows(
    data.frame(
      state = "US median*",
      # Technically, they say "just over seven hours" so I added 5% to SAIDI.
      # SAIFI is interpreted from graph
      saidi = 7*1.05,
      saifi = 1.4
    )
  ) %>% 
  mutate(
    state = fct_reorder(state, saidi)
  ) %>% 
  ggplot(aes(x = saidi,
             y = saifi)) +
  geom_point(aes(color = state == "US median*"),
             size = rel(4),
             alpha = 1/1.5) +
  geom_text_repel(aes(color = state == "US median*",
                      label = state)) +
  scale_color_manual(values = c(base_red,
                                median_red)) +
  expand_limits(x = 0,
                y = 0) +
  labs(title = paste("States' SAIDIs & SAIFIs compared to the", median_tag), 
       caption = "*including major events") +
  guides(color = "none") +
  theme(panel.grid.major = element_line("grey90"),
        axis.title = element_blank(),
        title = element_markdown(size = rel(0.8)))
```

